// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tradedetail.proto

package GrpcTradeDetail

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GrpcTradeDetailObject struct {
	ID      int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Money   string `protobuf:"bytes,2,opt,name=Money,proto3" json:"Money,omitempty"`
	Type    string `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"`
	PayName string `protobuf:"bytes,4,opt,name=PayName,proto3" json:"PayName,omitempty"`
	//google.protobuf.Timestamp TradeDate = 5;
	TradeDate            string   `protobuf:"bytes,5,opt,name=TradeDate,proto3" json:"TradeDate,omitempty"`
	Balance              string   `protobuf:"bytes,6,opt,name=Balance,proto3" json:"Balance,omitempty"`
	UserID               string   `protobuf:"bytes,7,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrpcTradeDetailObject) Reset()         { *m = GrpcTradeDetailObject{} }
func (m *GrpcTradeDetailObject) String() string { return proto.CompactTextString(m) }
func (*GrpcTradeDetailObject) ProtoMessage()    {}
func (*GrpcTradeDetailObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d491e32b3f10e9f, []int{0}
}

func (m *GrpcTradeDetailObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcTradeDetailObject.Unmarshal(m, b)
}
func (m *GrpcTradeDetailObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcTradeDetailObject.Marshal(b, m, deterministic)
}
func (m *GrpcTradeDetailObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcTradeDetailObject.Merge(m, src)
}
func (m *GrpcTradeDetailObject) XXX_Size() int {
	return xxx_messageInfo_GrpcTradeDetailObject.Size(m)
}
func (m *GrpcTradeDetailObject) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcTradeDetailObject.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcTradeDetailObject proto.InternalMessageInfo

func (m *GrpcTradeDetailObject) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *GrpcTradeDetailObject) GetMoney() string {
	if m != nil {
		return m.Money
	}
	return ""
}

func (m *GrpcTradeDetailObject) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GrpcTradeDetailObject) GetPayName() string {
	if m != nil {
		return m.PayName
	}
	return ""
}

func (m *GrpcTradeDetailObject) GetTradeDate() string {
	if m != nil {
		return m.TradeDate
	}
	return ""
}

func (m *GrpcTradeDetailObject) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *GrpcTradeDetailObject) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GrpcTradeDetailSel struct {
	ID      int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Money   string `protobuf:"bytes,2,opt,name=Money,proto3" json:"Money,omitempty"`
	Type    string `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"`
	PayName string `protobuf:"bytes,4,opt,name=PayName,proto3" json:"PayName,omitempty"`
	//google.protobuf.Timestamp TradeDate = 5;
	TradeDate            string   `protobuf:"bytes,5,opt,name=TradeDate,proto3" json:"TradeDate,omitempty"`
	Balance              string   `protobuf:"bytes,6,opt,name=Balance,proto3" json:"Balance,omitempty"`
	UserID               string   `protobuf:"bytes,7,opt,name=UserID,proto3" json:"UserID,omitempty"`
	StartTradeDate       string   `protobuf:"bytes,8,opt,name=StartTradeDate,proto3" json:"StartTradeDate,omitempty"`
	EndTradeDate         string   `protobuf:"bytes,9,opt,name=EndTradeDate,proto3" json:"EndTradeDate,omitempty"`
	Page                 int32    `protobuf:"varint,15,opt,name=page,proto3" json:"page,omitempty"`
	Pagecount            int32    `protobuf:"varint,16,opt,name=pagecount,proto3" json:"pagecount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrpcTradeDetailSel) Reset()         { *m = GrpcTradeDetailSel{} }
func (m *GrpcTradeDetailSel) String() string { return proto.CompactTextString(m) }
func (*GrpcTradeDetailSel) ProtoMessage()    {}
func (*GrpcTradeDetailSel) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d491e32b3f10e9f, []int{1}
}

func (m *GrpcTradeDetailSel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcTradeDetailSel.Unmarshal(m, b)
}
func (m *GrpcTradeDetailSel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcTradeDetailSel.Marshal(b, m, deterministic)
}
func (m *GrpcTradeDetailSel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcTradeDetailSel.Merge(m, src)
}
func (m *GrpcTradeDetailSel) XXX_Size() int {
	return xxx_messageInfo_GrpcTradeDetailSel.Size(m)
}
func (m *GrpcTradeDetailSel) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcTradeDetailSel.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcTradeDetailSel proto.InternalMessageInfo

func (m *GrpcTradeDetailSel) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *GrpcTradeDetailSel) GetMoney() string {
	if m != nil {
		return m.Money
	}
	return ""
}

func (m *GrpcTradeDetailSel) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GrpcTradeDetailSel) GetPayName() string {
	if m != nil {
		return m.PayName
	}
	return ""
}

func (m *GrpcTradeDetailSel) GetTradeDate() string {
	if m != nil {
		return m.TradeDate
	}
	return ""
}

func (m *GrpcTradeDetailSel) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *GrpcTradeDetailSel) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GrpcTradeDetailSel) GetStartTradeDate() string {
	if m != nil {
		return m.StartTradeDate
	}
	return ""
}

func (m *GrpcTradeDetailSel) GetEndTradeDate() string {
	if m != nil {
		return m.EndTradeDate
	}
	return ""
}

func (m *GrpcTradeDetailSel) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GrpcTradeDetailSel) GetPagecount() int32 {
	if m != nil {
		return m.Pagecount
	}
	return 0
}

type GrpcTradeDetailPage struct {
	Total                int32                    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Rows                 []*GrpcTradeDetailObject `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GrpcTradeDetailPage) Reset()         { *m = GrpcTradeDetailPage{} }
func (m *GrpcTradeDetailPage) String() string { return proto.CompactTextString(m) }
func (*GrpcTradeDetailPage) ProtoMessage()    {}
func (*GrpcTradeDetailPage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d491e32b3f10e9f, []int{2}
}

func (m *GrpcTradeDetailPage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcTradeDetailPage.Unmarshal(m, b)
}
func (m *GrpcTradeDetailPage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcTradeDetailPage.Marshal(b, m, deterministic)
}
func (m *GrpcTradeDetailPage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcTradeDetailPage.Merge(m, src)
}
func (m *GrpcTradeDetailPage) XXX_Size() int {
	return xxx_messageInfo_GrpcTradeDetailPage.Size(m)
}
func (m *GrpcTradeDetailPage) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcTradeDetailPage.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcTradeDetailPage proto.InternalMessageInfo

func (m *GrpcTradeDetailPage) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *GrpcTradeDetailPage) GetRows() []*GrpcTradeDetailObject {
	if m != nil {
		return m.Rows
	}
	return nil
}

func init() {
	proto.RegisterType((*GrpcTradeDetailObject)(nil), "GrpcTradeDetail.GrpcTradeDetailObject")
	proto.RegisterType((*GrpcTradeDetailSel)(nil), "GrpcTradeDetail.GrpcTradeDetailSel")
	proto.RegisterType((*GrpcTradeDetailPage)(nil), "GrpcTradeDetail.GrpcTradeDetailPage")
}

func init() { proto.RegisterFile("tradedetail.proto", fileDescriptor_2d491e32b3f10e9f) }

var fileDescriptor_2d491e32b3f10e9f = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x93, 0xb1, 0x6e, 0xe2, 0x40,
	0x10, 0x86, 0x65, 0x83, 0xe1, 0x98, 0x43, 0xc0, 0xcd, 0x71, 0xa7, 0xd5, 0xe9, 0x0a, 0xcb, 0x77,
	0x42, 0xae, 0x28, 0x48, 0x97, 0x12, 0x39, 0x8a, 0x28, 0x92, 0x10, 0x9b, 0x94, 0x29, 0x16, 0x33,
	0x42, 0x44, 0x8e, 0x6d, 0x2d, 0x0b, 0x91, 0x5f, 0x29, 0x0f, 0x90, 0x26, 0x2f, 0x17, 0xed, 0x98,
	0xc8, 0x89, 0x13, 0x89, 0x3a, 0x95, 0xf7, 0xff, 0xfe, 0xf9, 0x77, 0x67, 0x57, 0x63, 0xf8, 0xa1,
	0x95, 0x5c, 0xd1, 0x8a, 0xb4, 0xdc, 0x24, 0xe3, 0x5c, 0x65, 0x3a, 0xc3, 0xfe, 0xb9, 0xca, 0xe3,
	0x85, 0xc1, 0x01, 0x63, 0xef, 0xd9, 0x82, 0x5f, 0x35, 0x76, 0xb5, 0xbc, 0xa3, 0x58, 0x63, 0x0f,
	0xec, 0x59, 0x20, 0x2c, 0xd7, 0xf2, 0x1b, 0xa1, 0x3d, 0x0b, 0x70, 0x08, 0xce, 0x45, 0x96, 0x52,
	0x21, 0x6c, 0xd7, 0xf2, 0x3b, 0x61, 0x29, 0x10, 0xa1, 0xb9, 0x28, 0x72, 0x12, 0x0d, 0x86, 0xbc,
	0x46, 0x01, 0xed, 0xb9, 0x2c, 0x2e, 0xe5, 0x3d, 0x89, 0x26, 0xe3, 0x57, 0x89, 0x7f, 0xa1, 0x53,
	0x1e, 0x24, 0x35, 0x09, 0x87, 0xbd, 0x0a, 0x98, 0xdc, 0x54, 0x26, 0x32, 0x8d, 0x49, 0xb4, 0xca,
	0xdc, 0x41, 0xe2, 0x6f, 0x68, 0xdd, 0x6c, 0x49, 0xcd, 0x02, 0xd1, 0x66, 0xe3, 0xa0, 0xbc, 0x27,
	0x1b, 0xb0, 0xd6, 0x7d, 0x44, 0xc9, 0x57, 0x68, 0x1d, 0x47, 0xd0, 0x8b, 0xb4, 0x54, 0xba, 0xda,
	0xf4, 0x1b, 0xfb, 0x35, 0x8a, 0x1e, 0x74, 0xcf, 0xd2, 0x55, 0x55, 0xd5, 0xe1, 0xaa, 0x77, 0xcc,
	0xdc, 0x24, 0x97, 0x6b, 0x12, 0x7d, 0xd7, 0xf2, 0x9d, 0x90, 0xd7, 0xa6, 0x5f, 0xf3, 0x8d, 0xb3,
	0x5d, 0xaa, 0xc5, 0x80, 0x8d, 0x0a, 0x78, 0x6b, 0xf8, 0x59, 0x7b, 0xb7, 0xb9, 0x09, 0x0d, 0xc1,
	0xd1, 0x99, 0x96, 0x09, 0xbf, 0x9d, 0x13, 0x96, 0x02, 0x4f, 0xa1, 0xa9, 0xb2, 0x87, 0xad, 0xb0,
	0xdd, 0x86, 0xff, 0x7d, 0x32, 0x1a, 0xd7, 0x92, 0xe3, 0x4f, 0xe7, 0x27, 0xe4, 0xcc, 0x64, 0xff,
	0x61, 0xbc, 0x22, 0x52, 0x7b, 0x52, 0x78, 0x0b, 0x83, 0xeb, 0x1d, 0xa9, 0xe2, 0x8d, 0x83, 0xff,
	0x8e, 0x6d, 0x1d, 0x51, 0xf2, 0xe7, 0xff, 0xb1, 0x22, 0x73, 0x93, 0x69, 0xff, 0xd1, 0xee, 0x32,
	0x33, 0xc7, 0x6d, 0x62, 0x5a, 0xb6, 0xf8, 0x07, 0x38, 0x79, 0x09, 0x00, 0x00, 0xff, 0xff, 0x48,
	0x4a, 0x63, 0x66, 0x15, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GrpcTradeDetailServerClient is the client API for GrpcTradeDetailServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpcTradeDetailServerClient interface {
	QueryTradeDetail(ctx context.Context, in *GrpcTradeDetailSel, opts ...grpc.CallOption) (*GrpcTradeDetailPage, error)
}

type grpcTradeDetailServerClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcTradeDetailServerClient(cc grpc.ClientConnInterface) GrpcTradeDetailServerClient {
	return &grpcTradeDetailServerClient{cc}
}

func (c *grpcTradeDetailServerClient) QueryTradeDetail(ctx context.Context, in *GrpcTradeDetailSel, opts ...grpc.CallOption) (*GrpcTradeDetailPage, error) {
	out := new(GrpcTradeDetailPage)
	err := c.cc.Invoke(ctx, "/GrpcTradeDetail.GrpcTradeDetailServer/QueryTradeDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcTradeDetailServerServer is the server API for GrpcTradeDetailServer service.
type GrpcTradeDetailServerServer interface {
	QueryTradeDetail(context.Context, *GrpcTradeDetailSel) (*GrpcTradeDetailPage, error)
}

// UnimplementedGrpcTradeDetailServerServer can be embedded to have forward compatible implementations.
type UnimplementedGrpcTradeDetailServerServer struct {
}

func (*UnimplementedGrpcTradeDetailServerServer) QueryTradeDetail(ctx context.Context, req *GrpcTradeDetailSel) (*GrpcTradeDetailPage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryTradeDetail not implemented")
}

func RegisterGrpcTradeDetailServerServer(s *grpc.Server, srv GrpcTradeDetailServerServer) {
	s.RegisterService(&_GrpcTradeDetailServer_serviceDesc, srv)
}

func _GrpcTradeDetailServer_QueryTradeDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcTradeDetailSel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcTradeDetailServerServer).QueryTradeDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GrpcTradeDetail.GrpcTradeDetailServer/QueryTradeDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcTradeDetailServerServer).QueryTradeDetail(ctx, req.(*GrpcTradeDetailSel))
	}
	return interceptor(ctx, in, info, handler)
}

var _GrpcTradeDetailServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GrpcTradeDetail.GrpcTradeDetailServer",
	HandlerType: (*GrpcTradeDetailServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryTradeDetail",
			Handler:    _GrpcTradeDetailServer_QueryTradeDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tradedetail.proto",
}
