backen_service: #后端服务配置
  host: 127.0.0.1:5020
  token: xxx
redis_setting: #redis配置
  host: xxx:6379
  token: xxx
  secret: secret
  db: "1"
web_host: #主机监听地址配置
  host: 0.0.0.0:5030 #listen and serve on 0.0.0.0:5030
log_setting: #日志配置
  usefile: true #日志是否输出到文件
  usekafka: false #日志是否输出到kafka
kafka: #kafka配置
  host:
    - "localhost:9092"
    - "localhost:9091"
app_secret: #需要授权的服务secret，用secret换token
  - AuthCenter: 11
  - Trade:11


test: #测试嵌套类型解析
  - one:
      url: http://test
      nested: 123
  - two:
      url: http://test
      nested: 123